# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8560793b9cfbd064f69723dc3a4409a0b4890908de70d3ce661cef9782c20155d1dfdf3a116eb34619baf62d0e66061474be00788a4c9103a4187ad6dd4bbcd

test:
  secret_key_base: 5ddc32b3775470a33024e6f5b7ce353bf2524a248a5b1e3c334e1acb71c5eee8fe5c43bc07627e84690eb0d5283d97f03bba0cb38840768106c13002b2119c5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
